"""empty message

Revision ID: 2effadc46b31
Revises: e075ec73e53a
Create Date: 2020-08-09 00:38:39.585033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2effadc46b31'
down_revision = 'e075ec73e53a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'guest', ['email'])
    op.create_unique_constraint(None, 'user_account', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_account', type_='unique')
    op.drop_constraint(None, 'guest', type_='unique')
    # ### end Alembic commands ###
