"""empty message

Revision ID: 9e72b65b4d69
Revises: 70a01c7c2c0d
Create Date: 2020-08-15 22:42:50.733720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e72b65b4d69'
down_revision = '70a01c7c2c0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guest', 'email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_constraint('guest_email_key', 'guest', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('guest_email_key', 'guest', ['email'])
    op.alter_column('guest', 'email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###
