"""empty message

Revision ID: ea4c8e632ba4
Revises: 7a4758a135c4
Create Date: 2020-08-15 22:08:59.071555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea4c8e632ba4'
down_revision = '7a4758a135c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user_account', sa.Column('email', sa.String(length=255, collation='NOCASE'), nullable=False))
    op.add_column('user_account', sa.Column('email_confirmed_at', sa.DateTime(), nullable=True))
    op.alter_column('user_account', 'password',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_constraint('user_account_username_key', 'user_account', type_='unique')
    op.create_unique_constraint(None, 'user_account', ['email'])
    op.drop_column('user_account', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_account', type_='unique')
    op.create_unique_constraint('user_account_username_key', 'user_account', ['username'])
    op.alter_column('user_account', 'password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=60),
               existing_nullable=False)
    op.drop_column('user_account', 'email_confirmed_at')
    op.drop_column('user_account', 'email')
    op.drop_table('user_roles')
    op.drop_table('roles')
    op.drop_table('admin_account')
    # ### end Alembic commands ###
